-- Types Registry managed-state physical schema (P1).
--
-- PostgreSQL reference schema, not a migration. Migrations map identity, UUID,
-- binary, boolean, timestamp, and collation types to backend equivalents. Boolean
-- CHECKs must remain valid when lowered to SQLite INTEGER 0/1 or MySQL TINYINT(1).
-- JSON documents are stored as canonical UTF-8 text. Externally managed entities
-- are not stored here.
--
-- Every GTS Identifier, pattern, segment name, and family_key uses varchar(1024), binary
-- collation, and an ASCII character set where the backend default is multi-byte.
-- This preserves exact prefix-range semantics and keeps MySQL indexes within
-- InnoDB key limits.
--
-- Portable enumerations are stored as smallint. Their wire representation is a
-- string; numeric values are per-column, append-only after release, and constrained
-- by an explicit value list.


-- One ownership scope and serialization row per version family. It intentionally
-- carries no current member or aggregate version.
--
-- `family_key` removes the complete version and, for a type, the trailing kind
-- marker from the last segment; preceding segments remain unchanged:
--   gts.acme.crm.customer.type.v1.3~ -> gts.acme.crm.customer.type
--   gts.A.v1.2~B.v3~                 -> gts.A.v1.2~B
-- The result is an internal key, not a valid GTS Identifier.
--
-- Admission and purge lock this row to enforce family ownership, member-kind
-- consistency, and per-major minor shape/contiguity. Deleted members participate
-- until purged. Purging the last member removes the family and releases ownership.
CREATE TABLE types_registry__version_family (
    id               bigint        GENERATED BY DEFAULT AS IDENTITY,
    family_key       varchar(1024) COLLATE "C" NOT NULL,
    ownership_scope  smallint      NOT NULL, -- 1 global, 2 tenant
    owner_tenant_id  uuid          NULL,
    created_at       timestamptz   NOT NULL,

    CONSTRAINT pk_tr_version_family PRIMARY KEY (id),
    CONSTRAINT uq_tr_version_family_key UNIQUE (family_key),
    CONSTRAINT ck_tr_version_family_owner CHECK (
        (ownership_scope = 1 AND owner_tenant_id IS NULL)
        OR
        (ownership_scope = 2 AND owner_tenant_id IS NOT NULL)
    )
);


-- Scoped idempotency receipt and client-visible progress for one accepted
-- registration or deletion request. Candidate payloads and outcomes live in
-- operation_item. Worker delivery state lives in ToolKit-owned outbox tables.
--
-- `idempotency_scope_hash` covers plane, tenant, and principal without placing a
-- nullable tenant column in the unique key. `request_fingerprint` includes dry_run.
CREATE TABLE types_registry__operation (
    id                       uuid         NOT NULL,
    kind                     smallint     NOT NULL, -- 1 registration, 2 deletion
    dry_run                  boolean      NOT NULL,
    plane                    smallint     NOT NULL, -- 1 platform, 2 tenant
    tenant_id                uuid         NULL,
    -- The subject of the SecurityContext, which is a UUID there.
    principal_id             uuid         NOT NULL,
    idempotency_key          varchar(255) NOT NULL,
    idempotency_scope_hash   bytea        NOT NULL,
    request_fingerprint      bytea        NOT NULL,
    -- 1 pending, 2 running, 3 completed. Outcomes remain on operation_item.
    status                   smallint     NOT NULL,
    created_at               timestamptz  NOT NULL,
    started_at               timestamptz  NULL,
    completed_at             timestamptz  NULL,

    CONSTRAINT pk_tr_operation PRIMARY KEY (id),
    CONSTRAINT uq_tr_operation_idem
        UNIQUE (idempotency_scope_hash, idempotency_key),
    -- Target for the composite operation_item FK.
    CONSTRAINT uq_tr_operation_kind_mode UNIQUE (id, kind, dry_run),
    CONSTRAINT ck_tr_operation_kind CHECK (kind IN (1, 2)),
    CONSTRAINT ck_tr_operation_plane CHECK (
        (plane = 1 AND tenant_id IS NULL)            -- platform
        OR
        (plane = 2 AND tenant_id IS NOT NULL)        -- tenant
    ),
    CONSTRAINT ck_tr_operation_status CHECK (
        status IN (1, 2, 3)
    ),
    CONSTRAINT ck_tr_operation_state CHECK (
        (status = 1                                  -- pending
            AND started_at IS NULL
            AND completed_at IS NULL)
        OR
        (status = 2                                  -- running
            AND started_at IS NOT NULL
            AND completed_at IS NULL)
        OR
        (status = 3                                  -- completed
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL)
    )
);

-- Supports terminal-operation retention, which is measured from completed_at and
-- may remove an operation only when no revision references one of its items; item
-- status alone does not establish that condition.
CREATE INDEX idx_tr_operation_status
    ON types_registry__operation (status, completed_at, id);


-- One durable candidate and public result per exact GTS Identifier.
-- expected_resource_version is 0 for must-not-exist and otherwise names the version
-- to match. Entity resource versions start at 1.
--
-- `kind` and `dry_run` copy the parent values so the row-state CHECK can constrain
-- result fields without a cross-table expression. Terminal rows drop request_payload.
-- The write path creates revisions only for successful changed registrations;
-- those revision FKs pin operation history until purge removes them.
CREATE TABLE types_registry__operation_item (
    id                        bigint        GENERATED BY DEFAULT AS IDENTITY,
    operation_id              uuid          NOT NULL,
    item_no                   integer       NOT NULL, -- Zero-based request position
    gts_id                    varchar(1024) COLLATE "C" NOT NULL,
    -- Copied from operation; constrained by the composite FK below.
    dry_run                   boolean       NOT NULL,
    kind                      smallint      NOT NULL, -- 1 registration, 2 deletion
    -- 0 means the candidate must not exist; otherwise the version to match
    expected_resource_version bigint        NOT NULL,
    -- ADR-0004's accepted force: this candidate waives its one cross-minor
    -- compatibility check. Request-static and write-once. It is a column because
    -- admission is a separate pass that reads this row, and after T21 the outbox
    -- payload carries the operation UUID and nothing else -- so a waiver that is
    -- not stored is one the worker never sees, and type_schema_revision.compat_forced
    -- would record false on a revision whose check was in fact waived. Named for
    -- that destination column rather than for the wire field `force`, which MySQL
    -- reserves.
    compat_forced             boolean       NOT NULL DEFAULT false,
    -- 1 pending, 2 running, 3 succeeded, 4 unchanged, 5 failed.
    -- Status describes progress and outcome; error_payload describes failure causes.
    status                    smallint      NOT NULL,
    request_payload           text          NULL,
    result_revision_no        integer       NULL,
    result_resource_version   bigint        NULL,
    error_payload             text          NULL,
    created_at                timestamptz   NOT NULL,
    started_at                timestamptz   NULL,
    completed_at              timestamptz   NULL,

    CONSTRAINT pk_tr_operation_item PRIMARY KEY (id),
    CONSTRAINT uq_tr_operation_item_no
        UNIQUE (operation_id, item_no),
    CONSTRAINT uq_tr_operation_item_gts
        UNIQUE (operation_id, gts_id),
    -- Keeps copied kind/dry_run equal to the parent values.
    CONSTRAINT fk_tr_operation_item_operation
        FOREIGN KEY (operation_id, kind, dry_run)
        REFERENCES types_registry__operation (id, kind, dry_run) ON DELETE CASCADE,
    CONSTRAINT ck_tr_operation_item_no CHECK (item_no >= 0),
    CONSTRAINT ck_tr_operation_item_precondition
        CHECK (expected_resource_version >= 0),
    CONSTRAINT ck_tr_operation_item_revision
        CHECK (result_revision_no IS NULL OR result_revision_no >= 1),
    CONSTRAINT ck_tr_operation_item_resource_version
        CHECK (
            result_resource_version IS NULL
            OR result_resource_version >= 1
        ),
    CONSTRAINT ck_tr_operation_item_kind CHECK (kind IN (1, 2)),
    CONSTRAINT ck_tr_operation_item_status CHECK (
        status IN (1, 2, 3, 4, 5)
    ),
    CONSTRAINT ck_tr_operation_item_state CHECK (
        (status = 1                                  -- pending
            AND request_payload IS NOT NULL
            AND result_revision_no IS NULL
            AND result_resource_version IS NULL
            AND error_payload IS NULL
            AND started_at IS NULL
            AND completed_at IS NULL)
        OR
        (status = 2                                  -- running
            AND request_payload IS NOT NULL
            AND result_revision_no IS NULL
            AND result_resource_version IS NULL
            AND error_payload IS NULL
            AND started_at IS NOT NULL
            AND completed_at IS NULL)
        OR
        (status IN (3, 4)                            -- succeeded, unchanged
            AND request_payload IS NULL
            AND error_payload IS NULL
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL
            -- Only a committed, changed registration creates a content revision.
            AND (result_revision_no IS NOT NULL) = (NOT dry_run AND kind = 1 AND status = 3)
            -- `unchanged` is valid only for an update registration.
            AND (status <> 4 OR (kind = 1 AND expected_resource_version >= 1))
            -- Every committed result has a resource version. Dry-run `unchanged`
            -- reports the existing version; dry-run `succeeded` allocates none.
            AND (result_resource_version IS NOT NULL) = (NOT dry_run OR status = 4))
        OR
        (status = 5                                  -- failed
            AND request_payload IS NULL
            AND result_revision_no IS NULL
            AND result_resource_version IS NULL
            AND error_payload IS NOT NULL
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL)
    )
);

-- uq_tr_operation_item_no serves bounded per-operation polling in item order.


-- One logical managed entity per canonical GTS Identifier. Deleted rows remain as
-- tombstones so issued Registry References stay reverse-resolvable.
--
-- `gts_uuid`, `entity_kind` and `chain_depth` (`GtsId::segments().len()`) are
-- identifier-derived but materialized for portable lookup, constraints and
-- discovery filters. The write path verifies them and the ownership projection,
-- which is copied from version_family for scoped, join-free reads. `owning_gear` is
-- caller-declared attribution, never authority; it is required for global entities
-- and optional for tenant-owned entities.
--
-- resource_version starts at 1 and advances on committed entity-state changes,
-- including deletion. Content revision_no advances only when new authored content
-- is admitted; resolved-artifact recomputation advances neither value.
CREATE TABLE types_registry__entity (
    id                       bigint        GENERATED BY DEFAULT AS IDENTITY,
    gts_uuid                 uuid          NOT NULL,
    gts_id                   varchar(1024) COLLATE "C" NOT NULL,
    -- 1 type_schema, 2 instance
    entity_kind              smallint      NOT NULL,
    chain_depth              smallint      NOT NULL,
    family_id                bigint        NOT NULL,
    ownership_scope          smallint      NOT NULL, -- 1 global, 2 tenant
    owner_tenant_id          uuid          NULL,
    owning_gear              varchar(1024) NULL,
    lifecycle_status         smallint      NOT NULL, -- 1 active, 2 deleted
    resource_version         bigint        NOT NULL,
    deleted_at               timestamptz   NULL,
    created_at               timestamptz   NOT NULL,
    updated_at               timestamptz   NOT NULL,

    CONSTRAINT pk_tr_entity PRIMARY KEY (id),
    CONSTRAINT uq_tr_entity_gts_id UNIQUE (gts_id),
    CONSTRAINT uq_tr_entity_gts_uuid UNIQUE (gts_uuid),
    CONSTRAINT fk_tr_entity_family
        FOREIGN KEY (family_id)
        REFERENCES types_registry__version_family (id) ON DELETE RESTRICT,
    CONSTRAINT ck_tr_entity_kind
        CHECK (entity_kind IN (1, 2)),
    CONSTRAINT ck_tr_entity_chain_depth
        CHECK (chain_depth >= 1),
    CONSTRAINT ck_tr_entity_owner CHECK (
        (ownership_scope = 1                          -- global
            AND owner_tenant_id IS NULL
            AND owning_gear IS NOT NULL)
        OR
        (ownership_scope = 2                          -- tenant
            AND owner_tenant_id IS NOT NULL)
    ),
    CONSTRAINT ck_tr_entity_lifecycle CHECK (
        (lifecycle_status = 1 AND deleted_at IS NULL)     -- active
        OR
        (lifecycle_status = 2 AND deleted_at IS NOT NULL) -- deleted
    ),
    CONSTRAINT ck_tr_entity_resource_version
        CHECK (resource_version >= 1)
);

-- Covers exact family enumeration without identifier-pattern matching.
CREATE INDEX idx_tr_entity_family
    ON types_registry__entity (family_id, lifecycle_status, gts_id);

-- Main visibility/read index: one range for global entities and one per visible
-- tenant scope, combined with lifecycle and identifier bounds.
CREATE INDEX idx_tr_entity_visibility
    ON types_registry__entity (
        ownership_scope,
        owner_tenant_id,
        lifecycle_status,
        gts_id
    );

-- Serves discovery `depth=1` in `gts_id` order.
CREATE INDEX idx_tr_entity_depth
    ON types_registry__entity (chain_depth, gts_id);

-- Serves discovery by `kind` under one `lifecycle_status` in `gts_id` order.
-- `kind` leads so that a query without it cannot pick this index and sort: with
-- `lifecycle_status` first, MySQL did so for every page.
CREATE INDEX idx_tr_entity_kind_lifecycle
    ON types_registry__entity (entity_kind, lifecycle_status, gts_id);

-- Serves discovery under one `lifecycle_status` in `gts_id` order: tombstone-only
-- listings, and active pages with or without a pattern range, with no sort.
CREATE INDEX idx_tr_entity_lifecycle
    ON types_registry__entity (lifecycle_status, gts_id);


-- One row per parsed segment of entity.gts_id, written with the entity and never
-- updated. Discovery compiles a gts-rust-parsed pattern into one join per
-- constrained segment: exact name, major and type marker for a concrete segment,
-- minor only when the pattern names one; a name prefix range and optional major
-- for a trailing wildcard. Managed identifiers carry no UUID tail (ADR-0001).
CREATE TABLE types_registry__entity_gts_segment (
    entity_id     bigint        NOT NULL,
    segment_no    smallint      NOT NULL, -- 0-based chain position
    segment_name  varchar(1024) COLLATE "C" NOT NULL, -- vendor.package.namespace.type
    major         bigint        NOT NULL,
    minor         bigint        NULL,
    is_type       boolean       NOT NULL, -- segment ends with `~`

    CONSTRAINT pk_tr_entity_gts_segment PRIMARY KEY (entity_id, segment_no),
    CONSTRAINT fk_tr_entity_gts_segment_entity
        FOREIGN KEY (entity_id)
        REFERENCES types_registry__entity (id) ON DELETE CASCADE,
    CONSTRAINT ck_tr_entity_gts_segment_no CHECK (segment_no >= 0),
    CONSTRAINT ck_tr_entity_gts_segment_version
        CHECK (major >= 0 AND (minor IS NULL OR minor >= 0))
);

-- Lets a selective segment filter drive the discovery join.
CREATE INDEX idx_tr_entity_gts_segment_lookup
    ON types_registry__entity_gts_segment (
        segment_no,
        segment_name,
        major,
        is_type,
        minor,
        entity_id
    );


-- Type Schema admission snapshot: authored document and validation-engine
-- provenance. The write path treats snapshot fields as immutable;
-- the DDL does not enforce immutability. Resolved artifacts belong to current state.
-- operation_item_id retains the admitting operation provenance until purge.
CREATE TABLE types_registry__type_schema_revision (
    entity_id                  bigint       NOT NULL,
    revision_no                integer      NOT NULL,
    raw_schema                 text         NOT NULL,
    gts_spec_version           varchar(32)  NOT NULL,
    gts_impl_version           varchar(32)  NOT NULL,
    -- True when admission explicitly waived cross-minor compatibility.
    -- Always false for major-only entities and the first minor of a major.
    compat_forced              boolean      NOT NULL,
    operation_item_id          bigint       NOT NULL,
    created_at                 timestamptz  NOT NULL,
    updated_at                 timestamptz  NOT NULL,

    CONSTRAINT pk_tr_type_schema_revision PRIMARY KEY (entity_id, revision_no),
    CONSTRAINT uq_tr_type_schema_revision_item UNIQUE (operation_item_id),
    CONSTRAINT fk_tr_type_schema_revision_entity
        FOREIGN KEY (entity_id)
        REFERENCES types_registry__entity (id) ON DELETE CASCADE,
    CONSTRAINT fk_tr_type_schema_revision_item
        FOREIGN KEY (operation_item_id)
        REFERENCES types_registry__operation_item (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_tr_type_schema_revision_no CHECK (revision_no >= 1)
);

-- No content digest or index: `unchanged` compares canonical bytes with the
-- current revision only.


-- Instance admission snapshot, including the exact Type Schema revision that
-- validated it. The write path treats snapshot fields as immutable; the DDL does
-- not enforce immutability. type_schema_entity_id is derived from the Instance
-- identifier through its last `~` and materialized for the composite foreign key.
CREATE TABLE types_registry__instance_revision (
    entity_id                     bigint       NOT NULL,
    revision_no                   integer      NOT NULL,
    canonical_value               text         NOT NULL,
    type_schema_entity_id         bigint       NOT NULL,
    type_schema_revision_no       integer      NOT NULL,
    gts_spec_version              varchar(32)  NOT NULL,
    gts_impl_version              varchar(32)  NOT NULL,
    operation_item_id             bigint       NOT NULL,
    created_at                    timestamptz  NOT NULL,
    updated_at                    timestamptz  NOT NULL,

    CONSTRAINT pk_tr_instance_revision PRIMARY KEY (entity_id, revision_no),
    CONSTRAINT uq_tr_instance_revision_item UNIQUE (operation_item_id),
    CONSTRAINT fk_tr_instance_revision_entity
        FOREIGN KEY (entity_id)
        REFERENCES types_registry__entity (id) ON DELETE CASCADE,
    CONSTRAINT fk_tr_instance_revision_schema
        FOREIGN KEY (
            type_schema_entity_id,
            type_schema_revision_no
        )
        REFERENCES types_registry__type_schema_revision (
            entity_id,
            revision_no
        )
        ON DELETE RESTRICT,
    CONSTRAINT fk_tr_instance_revision_item
        FOREIGN KEY (operation_item_id)
        REFERENCES types_registry__operation_item (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_tr_instance_revision_no CHECK (revision_no >= 1)
);

-- No content digest or index; reverse dependency traversal drives schema revalidation.


-- Current Type Schema revision and its dependency-resolved artifacts. Authored
-- content and validation provenance remain in the immutable revision row.
--
-- resolution_fingerprint is an equality-only digest of canonical bytes for all
-- three artifacts. It changes when dependency-driven recomputation changes a read
-- result without advancing entity.resource_version.
CREATE TABLE types_registry__type_schema (
    entity_id                  bigint      NOT NULL,
    revision_no                integer     NOT NULL,
    resolved_schema            text        NOT NULL,
    effective_traits           text        NOT NULL,
    effective_traits_schema    text        NOT NULL,
    resolution_fingerprint     bytea       NOT NULL,
    created_at                 timestamptz NOT NULL,
    updated_at                 timestamptz NOT NULL,

    CONSTRAINT pk_tr_type_schema PRIMARY KEY (entity_id),
    CONSTRAINT fk_tr_type_schema_revision_ptr
        FOREIGN KEY (entity_id, revision_no)
        REFERENCES types_registry__type_schema_revision (
            entity_id,
            revision_no
        )
        ON DELETE CASCADE
);


-- Current registered Instance revision pointer. Authored value, validation
-- provenance, and the validating Type Schema revision remain in instance_revision.
CREATE TABLE types_registry__instance (
    entity_id   bigint      NOT NULL,
    revision_no integer     NOT NULL,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,

    CONSTRAINT pk_tr_instance PRIMARY KEY (entity_id),
    CONSTRAINT fk_tr_instance_revision_ptr
        FOREIGN KEY (entity_id, revision_no)
        REFERENCES types_registry__instance_revision (
            entity_id,
            revision_no
        )
        ON DELETE CASCADE
);


-- Direct dependency edges: from_entity_id depends on to_entity_id. Admission keeps
-- the combined edge set acyclic and replaces only the admitted entity's outgoing
-- rows. Transitive closure is computed at query time and is not stored.
--
-- Stored kinds are schema $ref, immediate derivation, and Instance conformance.
-- Derivation and conformance are materialized although identifier-derived.
-- `x-gts-ref` patterns are constraints, not dependency edges.
CREATE TABLE types_registry__dependency (
    from_entity_id bigint      NOT NULL,
    -- 1 schema_ref ($ref), 2 derivation (immediate base),
    -- 3 instance_of (conforming Type Schema)
    kind           smallint    NOT NULL,
    to_entity_id   bigint      NOT NULL,

    CONSTRAINT pk_tr_dependency
        PRIMARY KEY (from_entity_id, kind, to_entity_id),
    CONSTRAINT fk_tr_dependency_from
        FOREIGN KEY (from_entity_id)
        REFERENCES types_registry__entity (id) ON DELETE CASCADE,
    CONSTRAINT fk_tr_dependency_to
        FOREIGN KEY (to_entity_id)
        REFERENCES types_registry__entity (id) ON DELETE CASCADE,
    CONSTRAINT ck_tr_dependency_kind
        CHECK (kind IN (1, 2, 3))
);

-- Serves recursive reverse traversal and direct-dependent deletion checks.
CREATE INDEX idx_tr_dependency_to
    ON types_registry__dependency (to_entity_id, from_entity_id);


-- Installation-global coordination sequences. Migrations create and seed every
-- supported state; runtime code never creates rows implicitly and requires updates
-- to affect exactly one row.
--
-- Every transaction that changes entity state increments `entity_write_order` as
-- its first statement, before reads. This row lock serializes entity-state commits.
-- state_seq is monotonic; updated_at is observability metadata only.
CREATE TABLE types_registry__coordination_state (
    state_name  varchar(64) NOT NULL,
    state_seq   bigint      NOT NULL,
    updated_at  timestamptz NOT NULL,

    CONSTRAINT pk_tr_coordination_state PRIMARY KEY (state_name),
    CONSTRAINT ck_tr_coordination_state_seq CHECK (state_seq >= 0)
);


-- Base migrations seed `entity_write_order`; federation migrations also seed
-- `routing`, whose state_seq is the cache/cursor generation. A routing writer first
-- increments `entity_write_order`, then changes entity/claim state, and increments
-- `routing` as the transaction's final mutation. `routing` is not a separate
-- correctness lock.


-- Projection of a registered source-plugin Instance. Active claims and retired
-- reservations share a row because both reserve the identifier space:
-- retired_at IS NULL means active; Instance deletion sets retired_at. Purge
-- explicitly removes the claim before deleting its referenced revision.
--
-- priority (lower wins) and plugin_entity_gts_id are copied from the plugin for
-- join-free routing and overlap checks. Claims are kind-independent. Claims are
-- patterns matched against external identifiers, so no pattern-search index or
-- stored upper bound is used; the GTS matcher verifies every candidate claim.
CREATE TABLE types_registry__source_claim (
    id                         bigint        GENERATED BY DEFAULT AS IDENTITY,
    gts_id_pattern             varchar(1024) COLLATE "C" NOT NULL,
    plugin_entity_gts_id       varchar(1024) COLLATE "C" NOT NULL,
    plugin_entity_id           bigint        NOT NULL,
    plugin_entity_revision_no  integer       NOT NULL,
    priority                   smallint      NOT NULL,
    created_at                 timestamptz   NOT NULL,
    updated_at                 timestamptz   NOT NULL,
    retired_at                 timestamptz   NULL,  -- NULL means active

    CONSTRAINT pk_tr_source_claim PRIMARY KEY (id),
    CONSTRAINT uq_tr_source_claim_gts_id_pattern UNIQUE (gts_id_pattern),
    CONSTRAINT fk_tr_source_claim_plugin
        FOREIGN KEY (
            plugin_entity_id,
            plugin_entity_revision_no
        )
        REFERENCES types_registry__instance_revision (
            entity_id,
            revision_no
        )
        ON DELETE RESTRICT
);
