//! Initial Types Registry managed-state schema — the P0 subset of
//! `gears/system/types-registry/docs/database.sql`, which is the normative
//! target (SPEC §9).
//!
//! Nine of the eleven tables are created, in FK-dependency order:
//! `version_family`, `operation`, `operation_item`, `entity`,
//! `type_schema_revision`, `instance_revision`, `type_schema`, `instance`,
//! `dependency`. A later migration adds `coordination_state`; federation will add
//! `source_claim` and the `routing` state. No standalone `routing_config` exists.
//!
//! Outbox tables are not here either — they come from
//! `outbox_migrations_with_prefix("types_registry__outbox")`.
//!
//! # Tenant columns
//!
//! `ownership_scope`, `owner_tenant_id`, `plane` and `tenant_id` are created
//! with their CHECK constraints exactly as specified and are never populated
//! with tenant scope in P0: every row carries `ownership_scope = 1` /
//! `plane = 1` and a NULL tenant. Keeping the columns means P1 tenancy needs no
//! schema migration.
//!
//! # Per-backend lowering
//!
//! `database.sql` is `PostgreSQL`, so the Postgres list below is close to
//! verbatim. The other two lower it as follows.
//!
//! | `database.sql` | `SQLite` | `MySQL` |
//! |---|---|---|
//! | `bigint GENERATED BY DEFAULT AS IDENTITY` | `INTEGER PRIMARY KEY AUTOINCREMENT` | `BIGINT NOT NULL AUTO_INCREMENT` |
//! | `uuid` | `BLOB` + `length(x) = 16` | `BINARY(16)` |
//! | `varchar(1024) COLLATE "C"` | `TEXT COLLATE BINARY` | `VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin` |
//! | `bytea` | `BLOB` | `VARBINARY(64)` |
//! | `text` | `TEXT` | `LONGTEXT` |
//! | `boolean` | `INTEGER` + `IN (0, 1)` | `TINYINT(1)` + `IN (0, 1)` |
//! | `timestamptz` | `TEXT` | `DATETIME(6)` |
//!
//! Five points that are decisions rather than mechanics:
//!
//! * **`uuid` lowers to 16 raw bytes, not the 36-character text form** — dictated
//!   by the driver. `sqlx` encodes `Uuid` as `self.as_bytes()` on both backends and
//!   `sea-query` binds `Value::Uuid` straight through, so a `CHAR(36)` column
//!   receives binary: `MySQL` refuses it with `1366 Incorrect string value`, and
//!   `SQLite`, being dynamically typed, silently stores a blob in a `TEXT` column.
//!   `BINARY(16)` / `BLOB` describes what is actually stored and needs no
//!   per-column Rust type — the entities keep `Uuid`. `SQLite` also gets a
//!   `length(x) = 16` CHECK (`ck_tr_*_uuid_len`), because a declared `BLOB`
//!   constrains nothing there and raw SQL outside the ORM could still write text.
//!   `MySQL` needs none (fixed-width type); `PostgreSQL` keeps native `uuid`.
//! * **Identifier columns** (`entity.gts_id`, `version_family.family_key`,
//!   `operation_item.gts_id`) get binary collation on every backend, because
//!   pattern and derivation prefix ranges compile to explicit range bounds and must
//!   be exact. `SQLite`'s TEXT default *is* `BINARY`, stated anyway so a future
//!   `COLLATE NOCASE` cannot creep in. `MySQL` also gets an ASCII charset, keeping
//!   `uq_tr_entity_gts_id` inside `InnoDB`'s 3072-byte key limit — exact, because
//!   the GTS grammar is ASCII-only.
//! * **`MySQL` uses `DATETIME(6)`, not `TIMESTAMP(6)`.** With
//!   `explicit_defaults_for_timestamp` off, a table's first `TIMESTAMP` column
//!   silently acquires `DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
//!   which would rewrite `created_at` on every update.
//! * **The boolean-domain CHECKs on `SQLite` / `MySQL` are not additions to
//!   `database.sql`**: neither backend has a boolean type, so `IN (0, 1)`
//!   reproduces what Postgres's `boolean` guarantees. Without it `dry_run = 7`
//!   would store and `NOT dry_run` read as false inside
//!   `ck_tr_operation_item_state`.
//! * **`MySQL` declares its indexes inline** as `KEY` clauses. It has no
//!   `CREATE INDEX IF NOT EXISTS` and its DDL is not transactional, so an inline
//!   declaration is the only form covered by the table's own `IF NOT EXISTS`.
//!
//! No other CHECK, UNIQUE, PK, FK or index is added or dropped: the constraint
//! set is `database.sql`'s, one for one.

use sea_orm::{ConnectionTrait, Statement};
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

// ---------------------------------------------------------------------------
// PostgreSQL — the normative dialect.
// ---------------------------------------------------------------------------

const PG_UP_STATEMENTS: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS types_registry__version_family (
        id               bigint        GENERATED BY DEFAULT AS IDENTITY,
        family_key       varchar(1024) COLLATE \"C\" NOT NULL,
        ownership_scope  smallint      NOT NULL,
        owner_tenant_id  uuid          NULL,
        created_at       timestamptz   NOT NULL,

        CONSTRAINT pk_tr_version_family PRIMARY KEY (id),
        CONSTRAINT uq_tr_version_family_key UNIQUE (family_key),
        CONSTRAINT ck_tr_version_family_owner CHECK (
            (ownership_scope = 1 AND owner_tenant_id IS NULL)
            OR
            (ownership_scope = 2 AND owner_tenant_id IS NOT NULL)
        )
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__operation (
        id                       uuid         NOT NULL,
        kind                     smallint     NOT NULL,
        dry_run                  boolean      NOT NULL,
        plane                    smallint     NOT NULL,
        tenant_id                uuid         NULL,
        principal_id             uuid         NOT NULL,
        idempotency_key          varchar(255) NOT NULL,
        idempotency_scope_hash   bytea        NOT NULL,
        request_fingerprint      bytea        NOT NULL,
        status                   smallint     NOT NULL,
        created_at               timestamptz  NOT NULL,
        started_at               timestamptz  NULL,
        completed_at             timestamptz  NULL,

        CONSTRAINT pk_tr_operation PRIMARY KEY (id),
        CONSTRAINT uq_tr_operation_idem
            UNIQUE (idempotency_scope_hash, idempotency_key),
        CONSTRAINT uq_tr_operation_kind_mode UNIQUE (id, kind, dry_run),
        CONSTRAINT ck_tr_operation_kind CHECK (kind IN (1, 2)),
        CONSTRAINT ck_tr_operation_plane CHECK (
            (plane = 1 AND tenant_id IS NULL)
            OR
            (plane = 2 AND tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_operation_status CHECK (
            status IN (1, 2, 3)
        ),
        CONSTRAINT ck_tr_operation_state CHECK (
            (status = 1
                AND started_at IS NULL
                AND completed_at IS NULL)
            OR
            (status = 2
                AND started_at IS NOT NULL
                AND completed_at IS NULL)
            OR
            (status = 3
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL)
        )
    )",
    "CREATE INDEX IF NOT EXISTS idx_tr_operation_status
        ON types_registry__operation (status, completed_at, id)",
    "CREATE TABLE IF NOT EXISTS types_registry__operation_item (
        id                        bigint        GENERATED BY DEFAULT AS IDENTITY,
        operation_id              uuid          NOT NULL,
        item_no                   integer       NOT NULL,
        gts_id                    varchar(1024) COLLATE \"C\" NOT NULL,
        dry_run                   boolean       NOT NULL,
        kind                      smallint      NOT NULL,
        expected_resource_version bigint        NOT NULL,
        status                    smallint      NOT NULL,
        request_payload           text          NULL,
        result_revision_no        integer       NULL,
        result_resource_version   bigint        NULL,
        error_payload             text          NULL,
        created_at                timestamptz   NOT NULL,
        started_at                timestamptz   NULL,
        completed_at              timestamptz   NULL,

        CONSTRAINT pk_tr_operation_item PRIMARY KEY (id),
        CONSTRAINT uq_tr_operation_item_no
            UNIQUE (operation_id, item_no),
        CONSTRAINT uq_tr_operation_item_gts
            UNIQUE (operation_id, gts_id),
        CONSTRAINT fk_tr_operation_item_operation
            FOREIGN KEY (operation_id, kind, dry_run)
            REFERENCES types_registry__operation (id, kind, dry_run) ON DELETE CASCADE,
        CONSTRAINT ck_tr_operation_item_no CHECK (item_no >= 0),
        CONSTRAINT ck_tr_operation_item_precondition
            CHECK (expected_resource_version >= 0),
        CONSTRAINT ck_tr_operation_item_revision
            CHECK (result_revision_no IS NULL OR result_revision_no >= 1),
        CONSTRAINT ck_tr_operation_item_resource_version
            CHECK (
                result_resource_version IS NULL
                OR result_resource_version >= 1
            ),
        CONSTRAINT ck_tr_operation_item_kind CHECK (kind IN (1, 2)),
        CONSTRAINT ck_tr_operation_item_status CHECK (
            status IN (1, 2, 3, 4, 5)
        ),
        CONSTRAINT ck_tr_operation_item_state CHECK (
            (status = 1
                AND request_payload IS NOT NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NULL
                AND started_at IS NULL
                AND completed_at IS NULL)
            OR
            (status = 2
                AND request_payload IS NOT NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NULL
                AND started_at IS NOT NULL
                AND completed_at IS NULL)
            OR
            (status IN (3, 4)
                AND request_payload IS NULL
                AND error_payload IS NULL
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL
                AND (result_revision_no IS NOT NULL) = (NOT dry_run AND kind = 1 AND status = 3)
                AND (status <> 4 OR (kind = 1 AND expected_resource_version >= 1))
                AND (result_resource_version IS NOT NULL) = (NOT dry_run OR status = 4))
            OR
            (status = 5
                AND request_payload IS NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NOT NULL
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL)
        )
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__entity (
        id                       bigint        GENERATED BY DEFAULT AS IDENTITY,
        gts_uuid                 uuid          NOT NULL,
        gts_id                   varchar(1024) COLLATE \"C\" NOT NULL,
        entity_kind              smallint      NOT NULL,
        family_id                bigint        NOT NULL,
        ownership_scope          smallint      NOT NULL,
        owner_tenant_id          uuid          NULL,
        owning_gear              varchar(1024) NULL,
        lifecycle_status         smallint      NOT NULL,
        resource_version         bigint        NOT NULL,
        deleted_at               timestamptz   NULL,
        created_at               timestamptz   NOT NULL,
        updated_at               timestamptz   NOT NULL,

        CONSTRAINT pk_tr_entity PRIMARY KEY (id),
        CONSTRAINT uq_tr_entity_gts_id UNIQUE (gts_id),
        CONSTRAINT uq_tr_entity_gts_uuid UNIQUE (gts_uuid),
        CONSTRAINT fk_tr_entity_family
            FOREIGN KEY (family_id)
            REFERENCES types_registry__version_family (id) ON DELETE RESTRICT,
        CONSTRAINT ck_tr_entity_kind
            CHECK (entity_kind IN (1, 2)),
        CONSTRAINT ck_tr_entity_owner CHECK (
            (ownership_scope = 1
                AND owner_tenant_id IS NULL
                AND owning_gear IS NOT NULL)
            OR
            (ownership_scope = 2
                AND owner_tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_entity_lifecycle CHECK (
            (lifecycle_status = 1 AND deleted_at IS NULL)
            OR
            (lifecycle_status = 2 AND deleted_at IS NOT NULL)
        ),
        CONSTRAINT ck_tr_entity_resource_version
            CHECK (resource_version >= 1)
    )",
    "CREATE INDEX IF NOT EXISTS idx_tr_entity_family
        ON types_registry__entity (family_id, lifecycle_status, gts_id)",
    "CREATE INDEX IF NOT EXISTS idx_tr_entity_visibility
        ON types_registry__entity (
            ownership_scope,
            owner_tenant_id,
            lifecycle_status,
            gts_id
        )",
    "CREATE TABLE IF NOT EXISTS types_registry__type_schema_revision (
        entity_id                  bigint       NOT NULL,
        revision_no                integer      NOT NULL,
        raw_schema                 text         NOT NULL,
        content_hash               bytea        NOT NULL,
        gts_spec_version           varchar(32)  NOT NULL,
        gts_impl_version           varchar(32)  NOT NULL,
        compat_forced              boolean      NOT NULL,
        operation_item_id          bigint       NOT NULL,
        created_at                 timestamptz  NOT NULL,
        updated_at                 timestamptz  NOT NULL,

        CONSTRAINT pk_tr_type_schema_revision PRIMARY KEY (entity_id, revision_no),
        CONSTRAINT uq_tr_type_schema_revision_item UNIQUE (operation_item_id),
        CONSTRAINT fk_tr_type_schema_revision_entity
            FOREIGN KEY (entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_type_schema_revision_item
            FOREIGN KEY (operation_item_id)
            REFERENCES types_registry__operation_item (id)
            ON DELETE RESTRICT,
        CONSTRAINT ck_tr_type_schema_revision_no CHECK (revision_no >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__instance_revision (
        entity_id                     bigint       NOT NULL,
        revision_no                   integer      NOT NULL,
        canonical_value               text         NOT NULL,
        content_hash                  bytea        NOT NULL,
        type_schema_entity_id         bigint       NOT NULL,
        type_schema_revision_no       integer      NOT NULL,
        gts_spec_version              varchar(32)  NOT NULL,
        gts_impl_version              varchar(32)  NOT NULL,
        operation_item_id             bigint       NOT NULL,
        created_at                    timestamptz  NOT NULL,
        updated_at                    timestamptz  NOT NULL,

        CONSTRAINT pk_tr_instance_revision PRIMARY KEY (entity_id, revision_no),
        CONSTRAINT uq_tr_instance_revision_item UNIQUE (operation_item_id),
        CONSTRAINT fk_tr_instance_revision_entity
            FOREIGN KEY (entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_instance_revision_schema
            FOREIGN KEY (
                type_schema_entity_id,
                type_schema_revision_no
            )
            REFERENCES types_registry__type_schema_revision (
                entity_id,
                revision_no
            )
            ON DELETE RESTRICT,
        CONSTRAINT fk_tr_instance_revision_item
            FOREIGN KEY (operation_item_id)
            REFERENCES types_registry__operation_item (id)
            ON DELETE RESTRICT,
        CONSTRAINT ck_tr_instance_revision_no CHECK (revision_no >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__type_schema (
        entity_id                  bigint      NOT NULL,
        revision_no                integer     NOT NULL,
        resolved_schema            text        NOT NULL,
        effective_traits           text        NOT NULL,
        effective_traits_schema    text        NOT NULL,
        resolution_fingerprint     bytea       NOT NULL,
        created_at                 timestamptz NOT NULL,
        updated_at                 timestamptz NOT NULL,

        CONSTRAINT pk_tr_type_schema PRIMARY KEY (entity_id),
        CONSTRAINT fk_tr_type_schema_revision_ptr
            FOREIGN KEY (entity_id, revision_no)
            REFERENCES types_registry__type_schema_revision (
                entity_id,
                revision_no
            )
            ON DELETE CASCADE
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__instance (
        entity_id   bigint      NOT NULL,
        revision_no integer     NOT NULL,
        created_at  timestamptz NOT NULL,
        updated_at  timestamptz NOT NULL,

        CONSTRAINT pk_tr_instance PRIMARY KEY (entity_id),
        CONSTRAINT fk_tr_instance_revision_ptr
            FOREIGN KEY (entity_id, revision_no)
            REFERENCES types_registry__instance_revision (
                entity_id,
                revision_no
            )
            ON DELETE CASCADE
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__dependency (
        from_entity_id bigint      NOT NULL,
        kind           smallint    NOT NULL,
        to_entity_id   bigint      NOT NULL,

        CONSTRAINT pk_tr_dependency
            PRIMARY KEY (from_entity_id, kind, to_entity_id),
        CONSTRAINT fk_tr_dependency_from
            FOREIGN KEY (from_entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_dependency_to
            FOREIGN KEY (to_entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT ck_tr_dependency_kind
            CHECK (kind IN (1, 2, 3))
    )",
    "CREATE INDEX IF NOT EXISTS idx_tr_dependency_to
        ON types_registry__dependency (to_entity_id, from_entity_id)",
];

// ---------------------------------------------------------------------------
// SQLite — surrogate keys become `INTEGER PRIMARY KEY AUTOINCREMENT`, which
// SQLite only accepts inline, so those four tables lose the named `pk_`
// constraint. Everything else keeps its name.
// ---------------------------------------------------------------------------

const SQLITE_UP_STATEMENTS: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS types_registry__version_family (
        id               INTEGER  PRIMARY KEY AUTOINCREMENT,
        family_key       TEXT     COLLATE BINARY NOT NULL,
        ownership_scope  SMALLINT NOT NULL,
        owner_tenant_id  BLOB     NULL,
        created_at       TEXT     NOT NULL,

        CONSTRAINT uq_tr_version_family_key UNIQUE (family_key),
        CONSTRAINT ck_tr_version_family_owner CHECK (
            (ownership_scope = 1 AND owner_tenant_id IS NULL)
            OR
            (ownership_scope = 2 AND owner_tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_version_family_owner_uuid_len
            CHECK (owner_tenant_id IS NULL OR length(owner_tenant_id) = 16)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__operation (
        id                       BLOB     NOT NULL,
        kind                     SMALLINT NOT NULL,
        dry_run                  INTEGER  NOT NULL,
        plane                    SMALLINT NOT NULL,
        tenant_id                BLOB     NULL,
        principal_id             BLOB     NOT NULL,
        idempotency_key          TEXT     NOT NULL,
        idempotency_scope_hash   BLOB     NOT NULL,
        request_fingerprint      BLOB     NOT NULL,
        status                   SMALLINT NOT NULL,
        created_at               TEXT     NOT NULL,
        started_at               TEXT     NULL,
        completed_at             TEXT     NULL,

        CONSTRAINT pk_tr_operation PRIMARY KEY (id),
        CONSTRAINT uq_tr_operation_idem
            UNIQUE (idempotency_scope_hash, idempotency_key),
        CONSTRAINT uq_tr_operation_kind_mode UNIQUE (id, kind, dry_run),
        CONSTRAINT ck_tr_operation_kind CHECK (kind IN (1, 2)),
        CONSTRAINT ck_tr_operation_dry_run_bool CHECK (dry_run IN (0, 1)),
        CONSTRAINT ck_tr_operation_plane CHECK (
            (plane = 1 AND tenant_id IS NULL)
            OR
            (plane = 2 AND tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_operation_uuid_len CHECK (
            length(id) = 16
            AND (tenant_id IS NULL OR length(tenant_id) = 16)
            AND length(principal_id) = 16
        ),
        CONSTRAINT ck_tr_operation_status CHECK (
            status IN (1, 2, 3)
        ),
        CONSTRAINT ck_tr_operation_state CHECK (
            (status = 1
                AND started_at IS NULL
                AND completed_at IS NULL)
            OR
            (status = 2
                AND started_at IS NOT NULL
                AND completed_at IS NULL)
            OR
            (status = 3
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL)
        )
    )",
    "CREATE INDEX IF NOT EXISTS idx_tr_operation_status
        ON types_registry__operation (status, completed_at, id)",
    "CREATE TABLE IF NOT EXISTS types_registry__operation_item (
        id                        INTEGER  PRIMARY KEY AUTOINCREMENT,
        operation_id              BLOB     NOT NULL,
        item_no                   INTEGER  NOT NULL,
        gts_id                    TEXT     COLLATE BINARY NOT NULL,
        dry_run                   INTEGER  NOT NULL,
        kind                      SMALLINT NOT NULL,
        expected_resource_version BIGINT   NOT NULL,
        status                    SMALLINT NOT NULL,
        request_payload           TEXT     NULL,
        result_revision_no        INTEGER  NULL,
        result_resource_version   BIGINT   NULL,
        error_payload             TEXT     NULL,
        created_at                TEXT     NOT NULL,
        started_at                TEXT     NULL,
        completed_at              TEXT     NULL,

        CONSTRAINT uq_tr_operation_item_no
            UNIQUE (operation_id, item_no),
        CONSTRAINT uq_tr_operation_item_gts
            UNIQUE (operation_id, gts_id),
        CONSTRAINT fk_tr_operation_item_operation
            FOREIGN KEY (operation_id, kind, dry_run)
            REFERENCES types_registry__operation (id, kind, dry_run) ON DELETE CASCADE,
        CONSTRAINT ck_tr_operation_item_uuid_len
            CHECK (length(operation_id) = 16),
        CONSTRAINT ck_tr_operation_item_no CHECK (item_no >= 0),
        CONSTRAINT ck_tr_operation_item_dry_run_bool CHECK (dry_run IN (0, 1)),
        CONSTRAINT ck_tr_operation_item_precondition
            CHECK (expected_resource_version >= 0),
        CONSTRAINT ck_tr_operation_item_revision
            CHECK (result_revision_no IS NULL OR result_revision_no >= 1),
        CONSTRAINT ck_tr_operation_item_resource_version
            CHECK (
                result_resource_version IS NULL
                OR result_resource_version >= 1
            ),
        CONSTRAINT ck_tr_operation_item_kind CHECK (kind IN (1, 2)),
        CONSTRAINT ck_tr_operation_item_status CHECK (
            status IN (1, 2, 3, 4, 5)
        ),
        CONSTRAINT ck_tr_operation_item_state CHECK (
            (status = 1
                AND request_payload IS NOT NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NULL
                AND started_at IS NULL
                AND completed_at IS NULL)
            OR
            (status = 2
                AND request_payload IS NOT NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NULL
                AND started_at IS NOT NULL
                AND completed_at IS NULL)
            OR
            (status IN (3, 4)
                AND request_payload IS NULL
                AND error_payload IS NULL
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL
                AND (result_revision_no IS NOT NULL) = (NOT dry_run AND kind = 1 AND status = 3)
                AND (status <> 4 OR (kind = 1 AND expected_resource_version >= 1))
                AND (result_resource_version IS NOT NULL) = (NOT dry_run OR status = 4))
            OR
            (status = 5
                AND request_payload IS NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NOT NULL
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL)
        )
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__entity (
        id                       INTEGER  PRIMARY KEY AUTOINCREMENT,
        gts_uuid                 BLOB     NOT NULL,
        gts_id                   TEXT     COLLATE BINARY NOT NULL,
        entity_kind              SMALLINT NOT NULL,
        family_id                BIGINT   NOT NULL,
        ownership_scope          SMALLINT NOT NULL,
        owner_tenant_id          BLOB     NULL,
        owning_gear              TEXT     NULL,
        lifecycle_status         SMALLINT NOT NULL,
        resource_version         BIGINT   NOT NULL,
        deleted_at               TEXT     NULL,
        created_at               TEXT     NOT NULL,
        updated_at               TEXT     NOT NULL,

        CONSTRAINT uq_tr_entity_gts_id UNIQUE (gts_id),
        CONSTRAINT uq_tr_entity_gts_uuid UNIQUE (gts_uuid),
        CONSTRAINT fk_tr_entity_family
            FOREIGN KEY (family_id)
            REFERENCES types_registry__version_family (id) ON DELETE RESTRICT,
        CONSTRAINT ck_tr_entity_uuid_len CHECK (
            length(gts_uuid) = 16
            AND (owner_tenant_id IS NULL OR length(owner_tenant_id) = 16)
        ),
        CONSTRAINT ck_tr_entity_kind
            CHECK (entity_kind IN (1, 2)),
        CONSTRAINT ck_tr_entity_owner CHECK (
            (ownership_scope = 1
                AND owner_tenant_id IS NULL
                AND owning_gear IS NOT NULL)
            OR
            (ownership_scope = 2
                AND owner_tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_entity_lifecycle CHECK (
            (lifecycle_status = 1 AND deleted_at IS NULL)
            OR
            (lifecycle_status = 2 AND deleted_at IS NOT NULL)
        ),
        CONSTRAINT ck_tr_entity_resource_version
            CHECK (resource_version >= 1)
    )",
    "CREATE INDEX IF NOT EXISTS idx_tr_entity_family
        ON types_registry__entity (family_id, lifecycle_status, gts_id)",
    "CREATE INDEX IF NOT EXISTS idx_tr_entity_visibility
        ON types_registry__entity (
            ownership_scope,
            owner_tenant_id,
            lifecycle_status,
            gts_id
        )",
    "CREATE TABLE IF NOT EXISTS types_registry__type_schema_revision (
        entity_id                  BIGINT      NOT NULL,
        revision_no                INTEGER     NOT NULL,
        raw_schema                 TEXT        NOT NULL,
        content_hash               BLOB        NOT NULL,
        gts_spec_version           VARCHAR(32) NOT NULL,
        gts_impl_version           VARCHAR(32) NOT NULL,
        compat_forced              INTEGER     NOT NULL,
        operation_item_id          BIGINT      NOT NULL,
        created_at                 TEXT        NOT NULL,
        updated_at                 TEXT        NOT NULL,

        CONSTRAINT pk_tr_type_schema_revision PRIMARY KEY (entity_id, revision_no),
        CONSTRAINT uq_tr_type_schema_revision_item UNIQUE (operation_item_id),
        CONSTRAINT fk_tr_type_schema_revision_entity
            FOREIGN KEY (entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_type_schema_revision_item
            FOREIGN KEY (operation_item_id)
            REFERENCES types_registry__operation_item (id)
            ON DELETE RESTRICT,
        CONSTRAINT ck_tr_type_schema_revision_compat_forced_bool
            CHECK (compat_forced IN (0, 1)),
        CONSTRAINT ck_tr_type_schema_revision_no CHECK (revision_no >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__instance_revision (
        entity_id                     BIGINT      NOT NULL,
        revision_no                   INTEGER     NOT NULL,
        canonical_value               TEXT        NOT NULL,
        content_hash                  BLOB        NOT NULL,
        type_schema_entity_id         BIGINT      NOT NULL,
        type_schema_revision_no       INTEGER     NOT NULL,
        gts_spec_version              VARCHAR(32) NOT NULL,
        gts_impl_version              VARCHAR(32) NOT NULL,
        operation_item_id             BIGINT      NOT NULL,
        created_at                    TEXT        NOT NULL,
        updated_at                    TEXT        NOT NULL,

        CONSTRAINT pk_tr_instance_revision PRIMARY KEY (entity_id, revision_no),
        CONSTRAINT uq_tr_instance_revision_item UNIQUE (operation_item_id),
        CONSTRAINT fk_tr_instance_revision_entity
            FOREIGN KEY (entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_instance_revision_schema
            FOREIGN KEY (
                type_schema_entity_id,
                type_schema_revision_no
            )
            REFERENCES types_registry__type_schema_revision (
                entity_id,
                revision_no
            )
            ON DELETE RESTRICT,
        CONSTRAINT fk_tr_instance_revision_item
            FOREIGN KEY (operation_item_id)
            REFERENCES types_registry__operation_item (id)
            ON DELETE RESTRICT,
        CONSTRAINT ck_tr_instance_revision_no CHECK (revision_no >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__type_schema (
        entity_id                  BIGINT  NOT NULL,
        revision_no                INTEGER NOT NULL,
        resolved_schema            TEXT    NOT NULL,
        effective_traits           TEXT    NOT NULL,
        effective_traits_schema    TEXT    NOT NULL,
        resolution_fingerprint     BLOB    NOT NULL,
        created_at                 TEXT    NOT NULL,
        updated_at                 TEXT    NOT NULL,

        CONSTRAINT pk_tr_type_schema PRIMARY KEY (entity_id),
        CONSTRAINT fk_tr_type_schema_revision_ptr
            FOREIGN KEY (entity_id, revision_no)
            REFERENCES types_registry__type_schema_revision (
                entity_id,
                revision_no
            )
            ON DELETE CASCADE
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__instance (
        entity_id   BIGINT  NOT NULL,
        revision_no INTEGER NOT NULL,
        created_at  TEXT    NOT NULL,
        updated_at  TEXT    NOT NULL,

        CONSTRAINT pk_tr_instance PRIMARY KEY (entity_id),
        CONSTRAINT fk_tr_instance_revision_ptr
            FOREIGN KEY (entity_id, revision_no)
            REFERENCES types_registry__instance_revision (
                entity_id,
                revision_no
            )
            ON DELETE CASCADE
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__dependency (
        from_entity_id BIGINT   NOT NULL,
        kind           SMALLINT NOT NULL,
        to_entity_id   BIGINT   NOT NULL,

        CONSTRAINT pk_tr_dependency
            PRIMARY KEY (from_entity_id, kind, to_entity_id),
        CONSTRAINT fk_tr_dependency_from
            FOREIGN KEY (from_entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_dependency_to
            FOREIGN KEY (to_entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT ck_tr_dependency_kind
            CHECK (kind IN (1, 2, 3))
    )",
    "CREATE INDEX IF NOT EXISTS idx_tr_dependency_to
        ON types_registry__dependency (to_entity_id, from_entity_id)",
];

// ---------------------------------------------------------------------------
// MySQL — indexes are declared inline (no `CREATE INDEX IF NOT EXISTS`), and
// `DATETIME(6)` replaces `timestamptz` so no column picks up an implicit
// `ON UPDATE CURRENT_TIMESTAMP`.
// ---------------------------------------------------------------------------

const MYSQL_UP_STATEMENTS: &[&str] = &[
    "CREATE TABLE IF NOT EXISTS types_registry__version_family (
        id               BIGINT       NOT NULL AUTO_INCREMENT,
        family_key       VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
        ownership_scope  SMALLINT     NOT NULL,
        owner_tenant_id  BINARY(16)   NULL,
        created_at       DATETIME(6)  NOT NULL,

        CONSTRAINT pk_tr_version_family PRIMARY KEY (id),
        CONSTRAINT uq_tr_version_family_key UNIQUE (family_key),
        CONSTRAINT ck_tr_version_family_owner CHECK (
            (ownership_scope = 1 AND owner_tenant_id IS NULL)
            OR
            (ownership_scope = 2 AND owner_tenant_id IS NOT NULL)
        )
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__operation (
        id                       BINARY(16)    NOT NULL,
        kind                     SMALLINT      NOT NULL,
        dry_run                  TINYINT(1)    NOT NULL,
        plane                    SMALLINT      NOT NULL,
        tenant_id                BINARY(16)    NULL,
        principal_id             BINARY(16)    NOT NULL,
        idempotency_key          VARCHAR(255)  NOT NULL,
        idempotency_scope_hash   VARBINARY(64) NOT NULL,
        request_fingerprint      VARBINARY(64) NOT NULL,
        status                   SMALLINT      NOT NULL,
        created_at               DATETIME(6)   NOT NULL,
        started_at               DATETIME(6)   NULL,
        completed_at             DATETIME(6)   NULL,

        CONSTRAINT pk_tr_operation PRIMARY KEY (id),
        CONSTRAINT uq_tr_operation_idem
            UNIQUE (idempotency_scope_hash, idempotency_key),
        CONSTRAINT uq_tr_operation_kind_mode UNIQUE (id, kind, dry_run),
        KEY idx_tr_operation_status (status, completed_at, id),
        CONSTRAINT ck_tr_operation_kind CHECK (kind IN (1, 2)),
        CONSTRAINT ck_tr_operation_dry_run_bool CHECK (dry_run IN (0, 1)),
        CONSTRAINT ck_tr_operation_plane CHECK (
            (plane = 1 AND tenant_id IS NULL)
            OR
            (plane = 2 AND tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_operation_status CHECK (
            status IN (1, 2, 3)
        ),
        CONSTRAINT ck_tr_operation_state CHECK (
            (status = 1
                AND started_at IS NULL
                AND completed_at IS NULL)
            OR
            (status = 2
                AND started_at IS NOT NULL
                AND completed_at IS NULL)
            OR
            (status = 3
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL)
        )
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__operation_item (
        id                        BIGINT       NOT NULL AUTO_INCREMENT,
        operation_id              BINARY(16)   NOT NULL,
        item_no                   INT          NOT NULL,
        gts_id                    VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
        dry_run                   TINYINT(1)   NOT NULL,
        kind                      SMALLINT     NOT NULL,
        expected_resource_version BIGINT       NOT NULL,
        status                    SMALLINT     NOT NULL,
        request_payload           LONGTEXT     NULL,
        result_revision_no        INT          NULL,
        result_resource_version   BIGINT       NULL,
        error_payload             LONGTEXT     NULL,
        created_at                DATETIME(6)  NOT NULL,
        started_at                DATETIME(6)  NULL,
        completed_at              DATETIME(6)  NULL,

        CONSTRAINT pk_tr_operation_item PRIMARY KEY (id),
        CONSTRAINT uq_tr_operation_item_no
            UNIQUE (operation_id, item_no),
        CONSTRAINT uq_tr_operation_item_gts
            UNIQUE (operation_id, gts_id),
        CONSTRAINT fk_tr_operation_item_operation
            FOREIGN KEY (operation_id, kind, dry_run)
            REFERENCES types_registry__operation (id, kind, dry_run) ON DELETE CASCADE,
        CONSTRAINT ck_tr_operation_item_no CHECK (item_no >= 0),
        CONSTRAINT ck_tr_operation_item_dry_run_bool CHECK (dry_run IN (0, 1)),
        CONSTRAINT ck_tr_operation_item_precondition
            CHECK (expected_resource_version >= 0),
        CONSTRAINT ck_tr_operation_item_revision
            CHECK (result_revision_no IS NULL OR result_revision_no >= 1),
        CONSTRAINT ck_tr_operation_item_resource_version
            CHECK (
                result_resource_version IS NULL
                OR result_resource_version >= 1
            ),
        CONSTRAINT ck_tr_operation_item_kind CHECK (kind IN (1, 2)),
        CONSTRAINT ck_tr_operation_item_status CHECK (
            status IN (1, 2, 3, 4, 5)
        ),
        CONSTRAINT ck_tr_operation_item_state CHECK (
            (status = 1
                AND request_payload IS NOT NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NULL
                AND started_at IS NULL
                AND completed_at IS NULL)
            OR
            (status = 2
                AND request_payload IS NOT NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NULL
                AND started_at IS NOT NULL
                AND completed_at IS NULL)
            OR
            (status IN (3, 4)
                AND request_payload IS NULL
                AND error_payload IS NULL
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL
                AND (result_revision_no IS NOT NULL) = (NOT dry_run AND kind = 1 AND status = 3)
                AND (status <> 4 OR (kind = 1 AND expected_resource_version >= 1))
                AND (result_resource_version IS NOT NULL) = (NOT dry_run OR status = 4))
            OR
            (status = 5
                AND request_payload IS NULL
                AND result_revision_no IS NULL
                AND result_resource_version IS NULL
                AND error_payload IS NOT NULL
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL)
        )
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__entity (
        id                       BIGINT       NOT NULL AUTO_INCREMENT,
        gts_uuid                 BINARY(16)   NOT NULL,
        gts_id                   VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
        entity_kind              SMALLINT     NOT NULL,
        family_id                BIGINT       NOT NULL,
        ownership_scope          SMALLINT     NOT NULL,
        owner_tenant_id          BINARY(16)   NULL,
        owning_gear              VARCHAR(1024) NULL,
        lifecycle_status         SMALLINT     NOT NULL,
        resource_version         BIGINT       NOT NULL,
        deleted_at               DATETIME(6)  NULL,
        created_at               DATETIME(6)  NOT NULL,
        updated_at               DATETIME(6)  NOT NULL,

        CONSTRAINT pk_tr_entity PRIMARY KEY (id),
        CONSTRAINT uq_tr_entity_gts_id UNIQUE (gts_id),
        CONSTRAINT uq_tr_entity_gts_uuid UNIQUE (gts_uuid),
        KEY idx_tr_entity_family (family_id, lifecycle_status, gts_id),
        KEY idx_tr_entity_visibility (
            ownership_scope,
            owner_tenant_id,
            lifecycle_status,
            gts_id
        ),
        CONSTRAINT fk_tr_entity_family
            FOREIGN KEY (family_id)
            REFERENCES types_registry__version_family (id) ON DELETE RESTRICT,
        CONSTRAINT ck_tr_entity_kind
            CHECK (entity_kind IN (1, 2)),
        CONSTRAINT ck_tr_entity_owner CHECK (
            (ownership_scope = 1
                AND owner_tenant_id IS NULL
                AND owning_gear IS NOT NULL)
            OR
            (ownership_scope = 2
                AND owner_tenant_id IS NOT NULL)
        ),
        CONSTRAINT ck_tr_entity_lifecycle CHECK (
            (lifecycle_status = 1 AND deleted_at IS NULL)
            OR
            (lifecycle_status = 2 AND deleted_at IS NOT NULL)
        ),
        CONSTRAINT ck_tr_entity_resource_version
            CHECK (resource_version >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__type_schema_revision (
        entity_id                  BIGINT        NOT NULL,
        revision_no                INT           NOT NULL,
        raw_schema                 LONGTEXT      NOT NULL,
        content_hash               VARBINARY(64) NOT NULL,
        gts_spec_version           VARCHAR(32)   NOT NULL,
        gts_impl_version           VARCHAR(32)   NOT NULL,
        compat_forced              TINYINT(1)    NOT NULL,
        operation_item_id          BIGINT        NOT NULL,
        created_at                 DATETIME(6)   NOT NULL,
        updated_at                 DATETIME(6)   NOT NULL,

        CONSTRAINT pk_tr_type_schema_revision PRIMARY KEY (entity_id, revision_no),
        CONSTRAINT uq_tr_type_schema_revision_item UNIQUE (operation_item_id),
        CONSTRAINT fk_tr_type_schema_revision_entity
            FOREIGN KEY (entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_type_schema_revision_item
            FOREIGN KEY (operation_item_id)
            REFERENCES types_registry__operation_item (id)
            ON DELETE RESTRICT,
        CONSTRAINT ck_tr_type_schema_revision_compat_forced_bool
            CHECK (compat_forced IN (0, 1)),
        CONSTRAINT ck_tr_type_schema_revision_no CHECK (revision_no >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__instance_revision (
        entity_id                     BIGINT        NOT NULL,
        revision_no                   INT           NOT NULL,
        canonical_value               LONGTEXT      NOT NULL,
        content_hash                  VARBINARY(64) NOT NULL,
        type_schema_entity_id         BIGINT        NOT NULL,
        type_schema_revision_no       INT           NOT NULL,
        gts_spec_version              VARCHAR(32)   NOT NULL,
        gts_impl_version              VARCHAR(32)   NOT NULL,
        operation_item_id             BIGINT        NOT NULL,
        created_at                    DATETIME(6)   NOT NULL,
        updated_at                    DATETIME(6)   NOT NULL,

        CONSTRAINT pk_tr_instance_revision PRIMARY KEY (entity_id, revision_no),
        CONSTRAINT uq_tr_instance_revision_item UNIQUE (operation_item_id),
        CONSTRAINT fk_tr_instance_revision_entity
            FOREIGN KEY (entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_instance_revision_schema
            FOREIGN KEY (
                type_schema_entity_id,
                type_schema_revision_no
            )
            REFERENCES types_registry__type_schema_revision (
                entity_id,
                revision_no
            )
            ON DELETE RESTRICT,
        CONSTRAINT fk_tr_instance_revision_item
            FOREIGN KEY (operation_item_id)
            REFERENCES types_registry__operation_item (id)
            ON DELETE RESTRICT,
        CONSTRAINT ck_tr_instance_revision_no CHECK (revision_no >= 1)
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__type_schema (
        entity_id                  BIGINT        NOT NULL,
        revision_no                INT           NOT NULL,
        resolved_schema            LONGTEXT      NOT NULL,
        effective_traits           LONGTEXT      NOT NULL,
        effective_traits_schema    LONGTEXT      NOT NULL,
        resolution_fingerprint     VARBINARY(64) NOT NULL,
        created_at                 DATETIME(6)   NOT NULL,
        updated_at                 DATETIME(6)   NOT NULL,

        CONSTRAINT pk_tr_type_schema PRIMARY KEY (entity_id),
        CONSTRAINT fk_tr_type_schema_revision_ptr
            FOREIGN KEY (entity_id, revision_no)
            REFERENCES types_registry__type_schema_revision (
                entity_id,
                revision_no
            )
            ON DELETE CASCADE
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__instance (
        entity_id   BIGINT      NOT NULL,
        revision_no INT         NOT NULL,
        created_at  DATETIME(6) NOT NULL,
        updated_at  DATETIME(6) NOT NULL,

        CONSTRAINT pk_tr_instance PRIMARY KEY (entity_id),
        CONSTRAINT fk_tr_instance_revision_ptr
            FOREIGN KEY (entity_id, revision_no)
            REFERENCES types_registry__instance_revision (
                entity_id,
                revision_no
            )
            ON DELETE CASCADE
    )",
    "CREATE TABLE IF NOT EXISTS types_registry__dependency (
        from_entity_id BIGINT   NOT NULL,
        kind           SMALLINT NOT NULL,
        to_entity_id   BIGINT   NOT NULL,

        CONSTRAINT pk_tr_dependency
            PRIMARY KEY (from_entity_id, kind, to_entity_id),
        KEY idx_tr_dependency_to (to_entity_id, from_entity_id),
        CONSTRAINT fk_tr_dependency_from
            FOREIGN KEY (from_entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT fk_tr_dependency_to
            FOREIGN KEY (to_entity_id)
            REFERENCES types_registry__entity (id) ON DELETE CASCADE,
        CONSTRAINT ck_tr_dependency_kind
            CHECK (kind IN (1, 2, 3))
    )",
];

// ---------------------------------------------------------------------------
// Rollback — reverse FK-dependency order, identical on all three backends.
// ---------------------------------------------------------------------------

const DOWN_STATEMENTS: &[&str] = &[
    "DROP TABLE IF EXISTS types_registry__dependency",
    "DROP TABLE IF EXISTS types_registry__instance",
    "DROP TABLE IF EXISTS types_registry__type_schema",
    "DROP TABLE IF EXISTS types_registry__instance_revision",
    "DROP TABLE IF EXISTS types_registry__type_schema_revision",
    "DROP TABLE IF EXISTS types_registry__entity",
    "DROP TABLE IF EXISTS types_registry__operation_item",
    "DROP TABLE IF EXISTS types_registry__operation",
    "DROP TABLE IF EXISTS types_registry__version_family",
];

#[cfg(test)]
#[path = "m20260817_000001_initial_tests.rs"]
mod initial_tests;

// ---------------------------------------------------------------------------
// Migration dispatch.
// ---------------------------------------------------------------------------

/// `DatabaseBackend` is `#[non_exhaustive]`, so the dispatch below needs a
/// fallback arm. Returning an error rather than picking a dialect keeps the
/// schema from being created with DDL meant for a different engine.
fn unsupported_backend(backend: sea_orm::DatabaseBackend) -> DbErr {
    DbErr::Migration(format!(
        "types-registry migrations support Postgres, SQLite and MySQL only; \
         got unsupported database backend {backend:?}"
    ))
}

fn up_statements(backend: sea_orm::DatabaseBackend) -> Result<&'static [&'static str], DbErr> {
    match backend {
        sea_orm::DatabaseBackend::Postgres => Ok(PG_UP_STATEMENTS),
        sea_orm::DatabaseBackend::Sqlite => Ok(SQLITE_UP_STATEMENTS),
        sea_orm::DatabaseBackend::MySql => Ok(MYSQL_UP_STATEMENTS),
        other => Err(unsupported_backend(other)),
    }
}

// `MigrationTrait` is itself `#[async_trait]`-ified with an elided
// `SchemaManager<'_>` lifetime, so the impl must elide it too — spelling `<'_>`
// makes `async_trait` generate a different lifetime set and fails with E0195.
// The crate denies `rust_2018_idioms`, hence the targeted allow.
#[allow(elided_lifetimes_in_paths)]
#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let backend = manager.get_database_backend();
        let conn = manager.get_connection();
        for sql in up_statements(backend)? {
            conn.execute_raw(Statement::from_string(backend, (*sql).to_owned()))
                .await?;
        }
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let backend = manager.get_database_backend();
        // Reject the unsupported backend on the way down too: a `down` that
        // silently succeeds where `up` refused to run would report a rollback
        // that never happened.
        _ = up_statements(backend)?;
        let conn = manager.get_connection();
        for sql in DOWN_STATEMENTS {
            conn.execute_raw(Statement::from_string(backend, (*sql).to_owned()))
                .await?;
        }
        Ok(())
    }
}
