server:
  home_dir: "~/.cf-gears"

gears:
  api-gateway:
    config:
      bind_addr: "127.0.0.1:8087"
      enable_docs: true
      cors_enabled: false
      auth_disabled: true

  grpc-hub:
    config:
      listen_addr: "127.0.0.1:0"   # ephemeral port, passed to OoP child via env

  calculator-gateway:
    config: { }

  service-discovery:
    config: { }

  calculator:
    runtime:
      type: oop
      execution:
        executable_path: "./target/debug/calculator-oop"
        args: [ "--config", "config/oop-example-follower.yaml" ]

logging:
  default:
    console_level: debug
