apiVersion: v2
name: api-contracts
description: Deploys the api-contracts gear.
type: application
version: 0.1.0
appVersion: "dev"
dependencies:
  - name: toolkit-common
    version: 0.1.0
    repository: "file://../../../../../../deploy/helm/toolkit-common"
