//! The `SQLite` half of the schema oracle: is the dump an instrument we can trust?
//!
//! These cases do not compare the schema against anything. They establish the three properties
//! that have to hold before a comparison means anything at all — the dump is **deterministic**,
//! it is **complete**, and its normalisation **does not rewrite what it normalises**. An oracle
//! that fails any of those manufactures work or, worse, hides it.
//!
//! Task 1 of `tasks/plan.md`.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use sea_orm::Database;

mod schema_dump;

use schema_dump::{migrate_and_dump_sqlite, normalise_sql, tables_in};

/// Nineteen pricing tables plus coordination and toolkit delivery tables.
const PRICING_TABLES: usize = 19;

async fn migrated_dump() -> String {
    let conn = Database::connect("sqlite::memory:")
        .await
        .expect("connect in-memory sqlite");
    migrate_and_dump_sqlite(&conn).await
}

/// Two runs of the same chain, on two **separate** databases, dump identically.
///
/// Separate databases rather than two reads of one, because the property under test is that the
/// *chain* is deterministic, not that a `SELECT` is. A chain that seeded a uuid, a timestamp or a
/// hash into a constraint would pass the weaker version of this case and fail this one.
#[tokio::test]
async fn the_dump_of_one_chain_is_the_same_twice() {
    let first = migrated_dump().await;
    let second = migrated_dump().await;

    assert_eq!(
        first, second,
        "two runs of the same chain produced different dumps"
    );
    assert!(
        !first.is_empty(),
        "an empty dump is deterministic and worthless"
    );
}

/// The dump renders every table the chain creates.
///
/// The positive control is the count: a dump that filtered too hard would still be deterministic,
/// so determinism alone cannot tell a complete instrument from a broken one.
#[tokio::test]
async fn the_dump_names_every_table_the_chain_creates() {
    let dump = migrated_dump().await;
    let tables = tables_in(&dump);

    let pricing: Vec<&String> = tables
        .iter()
        .filter(|name| name.starts_with("pricing_"))
        .collect();
    assert_eq!(
        pricing.len(),
        PRICING_TABLES,
        "the dump names {} pricing tables, expected {PRICING_TABLES}: {pricing:?}",
        pricing.len()
    );

    assert_eq!(
        tables,
        vec![
            "bss_pricing_outbox_body".to_owned(),
            "bss_pricing_outbox_dead_letters".to_owned(),
            "bss_pricing_outbox_incoming".to_owned(),
            "bss_pricing_outbox_outgoing".to_owned(),
            "bss_pricing_outbox_partitions".to_owned(),
            "bss_pricing_outbox_processor".to_owned(),
            // The toolkit outbox's traced-batch table (main `0089c5398`).
            "bss_pricing_outbox_trace".to_owned(),
            "bss_pricing_outbox_vacuum_counter".to_owned(),
            "coord_leases".to_owned(),
            "event_broker_producer_registrations".to_owned(),
            "pricing_acceptance".to_owned(),
            "pricing_approval_decision".to_owned(),
            "pricing_approval_policy".to_owned(),
            "pricing_approval_unit".to_owned(),
            "pricing_approval_unit_item".to_owned(),
            "pricing_audit".to_owned(),
            "pricing_commercial_command".to_owned(),
            "pricing_dimension_key".to_owned(),
            "pricing_hold".to_owned(),
            "pricing_idempotency".to_owned(),
            "pricing_plan".to_owned(),
            "pricing_plan_item".to_owned(),
            "pricing_plan_revision".to_owned(),
            "pricing_price".to_owned(),
            "pricing_price_book".to_owned(),
            "pricing_price_book_entry".to_owned(),
            "pricing_reference_op".to_owned(),
            "pricing_settings".to_owned(),
            "pricing_usage_rating_policy".to_owned()
        ]
    );

    // Every stanza carries its DDL, so a table rendered with no definition would be a hole the
    // comparison could not see through.
    assert!(
        !dump.contains("<generated by the engine, not declared by the chain>"),
        "an engine-generated object reached the dump; the filter in schema_dump needs widening"
    );
}

/// Normalisation collapses formatting and leaves literals byte for byte.
///
/// This is the case that earns the normaliser its place. A trigger's
/// `RAISE(ABORT, 'a  message')` carries that string to the caller, so a whitespace collapse that
/// reached inside the quotes would rewrite an error message while every schema comparison stayed
/// green — the dump would agree with itself about a schema that had changed.
#[test]
fn normalisation_collapses_formatting_and_spares_literals() {
    // Collapsed: newlines and runs between tokens are formatting, and so is the space that sits
    // against a parenthesis.
    assert_eq!(
        normalise_sql("CREATE  TABLE\n  t (\n    a TEXT\n  )"),
        "CREATE TABLE t (a TEXT)"
    );

    // Spared: the run lives inside a literal.
    let raising = "CREATE TRIGGER g BEFORE INSERT ON t\n  BEGIN\n    SELECT RAISE(ABORT, 'two  spaces');\n  END";
    let out = normalise_sql(raising);
    assert!(
        out.contains("'two  spaces'"),
        "the literal lost its spacing: {out}"
    );

    // A doubled quote is SQLite's escape for a quote inside a literal. The run after it is still
    // inside the literal, so it is still spared -- the state machine must not read the escape as
    // a close.
    let escaped = "SELECT RAISE(ABORT, 'it''s  here')";
    assert!(
        normalise_sql(escaped).contains("'it''s  here'"),
        "a doubled quote was read as the end of the literal"
    );

    // A newline right after `CHECK (` is formatting too. Without this the byte-identical bar
    // would force a re-authored constraint to reproduce the line breaks of whichever historical
    // rebuild first spelled it.
    assert_eq!(
        normalise_sql("CHECK (\n    a > 0)"),
        normalise_sql("CHECK (a > 0)")
    );

    // The positive control for the whole idea: two spellings that differ only in formatting
    // normalise to one string, which is what lets a re-indented migration compare equal.
    assert_eq!(
        normalise_sql("CREATE INDEX i ON t (a,   b)"),
        normalise_sql("CREATE  INDEX i\n  ON t (a,\n       b)")
    );
}

/// The frozen dump: does today's chain still produce the schema we recorded?
///
/// This is the oracle the re-authoring is checked against. It is a golden file rather than an
/// in-test roster because the thing being pinned is the *whole* schema, and a roster written by
/// hand would pin the parts someone thought to list.
///
/// Re-record with `UPDATE_SCHEMA_GOLDEN=1`. Doing so is a claim that the schema was **meant** to
/// change; the diff this case prints is what has to justify it.
#[tokio::test]
async fn the_chain_still_produces_the_frozen_schema() {
    let golden_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/schema_golden/sqlite.txt"
    );
    let fresh = migrated_dump().await;

    // Capture a candidate for DDL review before explicitly updating the frozen oracle.
    if let Ok(path) = std::env::var("SCHEMA_REVIEW_PATH") {
        std::fs::write(path, &fresh).expect("write schema review candidate");
    }

    if std::env::var("UPDATE_SCHEMA_GOLDEN").is_ok() {
        let dir = std::path::Path::new(golden_path)
            .parent()
            .expect("the golden lives in a directory");
        std::fs::create_dir_all(dir).expect("create the golden directory");
        std::fs::write(golden_path, &fresh).expect("write the golden");
        return;
    }

    let golden = std::fs::read_to_string(golden_path).unwrap_or_else(|e| {
        panic!("no frozen schema at {golden_path} ({e}); record one with UPDATE_SCHEMA_GOLDEN=1")
    });

    if golden == fresh {
        return;
    }

    // Naming the first differing object beats "files differ": the stanza header a difference
    // falls under is the table, index or trigger whose definition moved, which is the one fact
    // the reader needs before opening either file.
    let mut object = "<before the first stanza>".to_owned();
    for (n, (want, got)) in golden.lines().zip(fresh.lines()).enumerate() {
        if !want.starts_with(' ') && !want.is_empty() {
            object = want.to_owned();
        }
        assert!(
            want == got,
            "the schema changed under {object}, at line {}:\n  frozen: {want}\n  now:    {got}",
            n + 1
        );
    }
    panic!(
        "the schema changed in length only: frozen has {} lines, now {}",
        golden.lines().count(),
        fresh.lines().count()
    );
}
