name: Docs

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - 'docs/**'
      - 'guidelines/**'
  workflow_dispatch:

concurrency:
  group: docs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdown_links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          clean: 'true'
          submodules: recursive

      - name: Install lychee
        uses: taiki-e/install-action@861a07ce7084f55488e375df125cdc99bba60eb7 # v2.87.23
        with:
          tool: lychee

      - name: Check markdown links
        run: make lychee
